### ISSUE TITLE
try to use existing vanjs code to create web component but error out

### ISSUE THREAD

**Issue by kangaroolab** [Atmos4/van-element#2]
Hi, I have following vanjs code for notebook, for which I tried to create a custom tag for it (see below) but I got following error. can you please help where the problem is and how I shall fix it?

error: 
Uncaught TypeError: e is not a function
    at HTMLElement.connectedCallback (van-element.browser.js:1:273)
    at Object.define (van-element.browser.js:1:73)
    at 94117346-67d9-4bcf-ab76-928584529019:58:8

```
<script src="https://cdn.jsdelivr.net/gh/vanjs-org/van/public/van-latest.nomodule.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanjs-element@latest/dist/van-element.browser.js"></script>

<div id="mytest" class="highlight">
  text goes here
</div>
<custom-counter></custom-counter>
<script>

        const { pre, br, div, span} = van.tags;

        // Notebook component
        const Notebook = (initialCode) => {
            const code = van.state("");
            const output = van.state("");

            // Function to run the code and update the output
            const runCode = () => {
                try {
                    const result = eval(code.val);
                    output.val = result;
                } catch (e) {
                    output.val = e.toString();
                }
            };

            // Function to update line numbers
            const updateLineNumbers = (textarea, lineNumbers) => {
                //const numberOfLines = textarea.value.split('\n').length;
                //const numberOfLines = textarea.innerText.split('\n').length;
                const numberOfLines = Math.max(textarea.getElementsByTagName("div").length, 1);
                lineNumbers.innerHTML = Array.from({ length: numberOfLines }, (_, i) => `<span>${i + 1}</span>`).join('');
            };

            const lineNumbers = div({ class: "line-numbers" });
            
            const codeTextarea = div({
                class: "codeTextarea",
                contenteditable: true,
                oninput: e => {
                    code.val = e.target.innerText;
                    updateLineNumbers(e.target, lineNumbers);
                },
                placeholder: "Write your code here...",
                style: "white-space: pre-wrap;", // Preserve whitespace and line breaks
                innerHTML: initialCode || ""
            });
            code.val = codeTextarea.innerText;
            updateLineNumbers(codeTextarea, lineNumbers);

            return div(
                { class: "code-editor" },
                div({ class: "code-container" }, lineNumbers, codeTextarea),
                div(
                    { class: "output-container" },
                    span({ class: "run-icon", onclick: runCode }, "▶️"),
                    div({ class: "code-output", textContent: output })
                )
            );
        };
        
  vanE.define("custom-counter", Notebook());
</script>
```

**Comment by sirenkovladd** [comment]
It looks like you have a mistake

You need to replace
```ts
vanE.define("custom-counter", Notebook());
```
to
```ts
vanE.define("custom-counter", Notebook);
```

**Comment by kangaroolab** [comment]
thanks...my bad.

after I fixed above, it doesn't display the component right. does van-element work with external css (e.g. all the classes in my code above like code-editor/code-container etc) or it has to be embedded in the web component itself?

**Comment by Atmos4** [comment]
@kangaroolab when using the Shadow DOM, the component will be isolated from the "external css". However, you can [disable the Shadow DOM](https://van-element.pages.dev/learn/shadow-options.html#disable-shadow-dom) in your case since you don't seem to use it:
```js
vanE.define("custom-counter", Notebook, false);
```

**Comment by Atmos4** [comment]
I will mark this issue as closed for now, but feel free to keep posting messages if you have more questions @kangaroolab

**Comment by kangaroolab** [comment]
thanks...disable virtual dom mode works.

one more question/issue, for below:

```
const codeTextarea = div({
                class: "codeTextarea",
                contenteditable: true,
                oninput: e => {
                    code.val = e.target.innerText;
                    updateLineNumbers(e.target, lineNumbers);
                },
                placeholder: "Write your code here...",
                style: "white-space: pre-wrap;", // Preserve whitespace and line breaks
                innerHTML: initialCode || ""
            });
```

it displays [object object] (related to innerHTML above). I don't have this problem if not using van element. any idea why and how to resolve it?

**Comment by sirenkovladd** [comment]
could you please send more code maybe to be able to run?

**Comment by Atmos4** [comment]
As said by @sirenkovladd we would need a bit more code to understand what you are trying to build. However it seems like you are trying to reproduce an example from VanJS: https://vanjs.org/demo#jupyter-like-javascript-console

@kangaroolab I managed to simplify your code a bit to come up with this version:
https://codepen.io/atmos4/pen/QWXPgqJ

If you want me to try and help with what you were trying to build (line numbers for a code editor) you need to provide us with your CSS!

**Comment by kangaroolab** [comment]
thank you both. here is html/JavaScript and css. I don't think it is css related but the line innerHTML: initialCode || "". if I don't use van element but vanjs.add, there is no such issue.

```
<script src="https://cdn.jsdelivr.net/gh/vanjs-org/van/public/van-latest.nomodule.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanjs-element@latest/dist/van-element.browser.js"></script>

<custom-counter></custom-counter>
<script>

        const { pre, br, div, span} = van.tags;

        // Notebook component
        const Notebook = (initialCode) => {
            const code = van.state("");
            const output = van.state("");

            // Function to run the code and update the output
            const runCode = () => {
                try {
                    const result = eval(code.val);
                    output.val = result;
                } catch (e) {
                    output.val = e.toString();
                }
            };

            // Function to update line numbers
            const updateLineNumbers = (textarea, lineNumbers) => {
                //const numberOfLines = textarea.value.split('\n').length;
                //const numberOfLines = textarea.innerText.split('\n').length;
                const numberOfLines = Math.max(textarea.getElementsByTagName("div").length, 1);
                lineNumbers.innerHTML = Array.from({ length: numberOfLines }, (_, i) => `<span>${i + 1}</span>`).join('');
            };

            const lineNumbers = div({ class: "line-numbers" });
            
            const codeTextarea = div({
                class: "codeTextarea",
                contenteditable: true,
                oninput: e => {
                    code.val = e.target.innerText;
                    updateLineNumbers(e.target, lineNumbers);
                },
                placeholder: "Write your code here...",
                style: "white-space: pre-wrap;", // Preserve whitespace and line breaks
                innerHTML: initialCode || ""
            });
            code.val = codeTextarea.innerText;
            updateLineNumbers(codeTextarea, lineNumbers);

            return div(
                { class: "code-editor" },
                div({ class: "code-container" }, lineNumbers, codeTextarea),
                div(
                    { class: "output-container" },
                    span({ class: "run-icon", onclick: runCode }, "▶️"),
                    div({ class: "code-output", textContent: output })
                )
            );
        };
 vanE.define("custom-counter", Notebook, false);
</script>
```

```
        .code-editor {
            display: flex;
            flex-direction: column;
            gap: 10px;
            border: 1px solid #ccc;
            padding: 10px;
        }
        .line-numbers {
            border-right: 1px solid #ccc;
            user-select: none;
            text-align: right;
            margin-right: 10px;
            white-space: pre-wrap;
            background-color: #f0f0f0;
            line-height: 1.2; /* Adjusted line height */
            font-size: 14px; /* Adjusted font size */
            padding: 5px; /* Optional: Add some padding for better spacing */
            font-family: monospace; /* Ensure consistent font */
            width: auto; /* Revert to previous width */
        }
        .line-numbers span {
            display: block;
            line-height: 1.2; /* Ensure line height matches textarea */
        }
        .code-container {
            display: flex;
        }
        textarea {
            width: 100%;
            height: 100px;
            border: none;
            outline: none;
            resize: none;
            line-height: 1.2; /* Adjusted line height to match line numbers */
            font-family: monospace; /* Ensure consistent font */
            font-size: 14px; /* Adjusted font size */
            padding: 5px; /* Ensure padding matches line numbers */
        }
        .codeTextarea {
            width: 100%;
            height: 100px;
            border: none;
            outline: none;
            resize: none;
            line-height: 1.2; /* Adjusted line height to match line numbers */
            font-family: monospace; /* Ensure consistent font */
            font-size: 14px; /* Adjusted font size */
            padding: 5px; /* Ensure padding matches line numbers */
        }
        .output-container {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .run-icon {
            cursor: pointer;
            font-size: 16px;
            width: auto; /* Match the width of line numbers */
            text-align: center; /* Center the icon */
        }
        .code-output {
            flex-grow: 1; /* Make the output take the remaining width */
            background-color: #f0f0f0; /* Set the background color */
            border: 1px solid #ccc;
            padding: 0 10px;
            display: inline-block;
            min-height: 16px;
            font-family: monospace; /* Ensure consistent font */
            font-size: 14px; /* Adjusted font size */
        }
```

**Comment by Atmos4** [comment]
`initialCode` will take the properties that are injected by van-element.

I don't know what you expected `initialCode` to be here. If you want it to be from the custom element's attribute, you need the following code:
```html
<custom-counter initial="some initial value"></custom-counter>
```
```js
const Notebook = ({ attr }) => {
  const initialValue = attr("initial");
  ...
}
``` 
You can find more information in [the documentation](https://van-element.pages.dev/learn/attributes.html
)
Here is the updated CodePen:
https://codepen.io/atmos4/pen/QWXPgqJ

**Comment by kangaroolab** [comment]
thanks...it works

**Comment by kangaroolab** [comment]
btw, instead of `<custom-counter initial="some initial value"></custom-counter>`,

is there a way to assign attribute like following:
let el = document.createElement("custom-counter");
el.initial = "some initial value";
document.body.appendChild(el);

this will help dynamically create new instance in the fly without showing the initial value in DOM (e.g. you can see it in inspector)

appreciate your help and advice.

**Comment by Atmos4** [comment]
You can use the [setAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) method to set the `initial` attribute!
```js
const element = document.createElement("custom-element");
element.setAttribute("initial", "some initial value");
```

**Comment by kangaroolab** [comment]
quick question - for tag name, do I have to always use '-' like custom-counter? can I do counter?

per your documentation, it doesn't say a specific format is required (see below). 
name Custom element tag.

but if I use counter, I got error.

btw does this work with van.tags?

**Comment by Atmos4** [comment]
@kangaroolab `van-element` is only a thin wrapper on top of custom elements, so it shares the same constraints when it comes to custom element naming. You can find a list of those constraints [here](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#valid_custom_element_names).

You can use custom elements with `van.tags` like this:
```js
const MyCustomComponent = () => van.tags["hello-world"]("I am a custom element");
```
Check out the [related section of the tutorial](https://van-element.pages.dev/intro/tutorial.html#reactive-van-elements)!
